import React, { useState } from "react";
import { Form } from "react-bootstrap";

export function EditMode(): JSX.Element {
    const [editMode, setEditMode] = useState<boolean>(false);
    const [name, setName] = useState<string>("Your Name");
    const [isStudent, setIsStudent] = useState<boolean>(true);

    const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setName(event.target.value);
    };

    const handleStudentChange = () => {
        setIsStudent(!isStudent);
    };

    const handleSwitchChange = () => {
        setEditMode(!editMode);
    };

    return (
        <div>
            <h3>Edit Mode</h3>
            <Form.Check
                type="switch"
                id="editSwitch"
                label="Edit Mode"
                checked={editMode}
                onChange={handleSwitchChange}
            />
            {editMode ? (
                <div>
                    <Form.Control
                        type="text"
                        placeholder="Your Name"
                        value={name}
                        onChange={handleNameChange}
                    />
                    <Form.Check
                        type="checkbox"
                        label="Student"
                        id="studentCheckbox"
                        checked={isStudent}
                        onChange={handleStudentChange}
                    />
                </div>
            ) : (
                <div>
                    <span>
                        {name} is {isStudent ? "a" : "not a"} student
                    </span>
                </div>
            )}
        </div>
    );
}
// partially generated by chatgpt
